---
# Use Ubuntu 14.04 LTS images, and explicitly require sudo.
# Relevant docs: https://docs.travis-ci.com/user/trusty-ci-environment/
sudo: required
dist: trusty
# Pin older version of Firefox, for Selenium compatibility. Must match version
# specified in app-test role vars!
addons:
  firefox: 46.0.1

# Setting language=generic to prevent Travis from setting up a virtualenv.
# Using a virtualenv conflicts with the global pip installation currently
# used for configuring SecureDrop, both in development and staging.
language: generic

before_install:
  - 'for e in /.packer-env/*; do echo -n "${e}: "; cat "${e}"; done'
  # Removes Travis-specific PATH customizations that affect Python.
  - export PATH="$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")"
  - printenv | sort # dump Travis environment for debugging
  - pip freeze -l
install:
  # Installing Python dependencies globally, to match SecureDrop deployment.
  - sudo -H pip install -r securedrop/requirements/develop-requirements.txt
  # Using YAML folding operator '>' to aid in readability and avoid
  # extremely long lines.
  - >
      printf
      "[development]\nlocalhost ansible_connection=local\n[travis]\nlocalhost"
      > inventory
  - >
      ansible-playbook -i inventory -vv --syntax-check
      install_files/ansible-base/securedrop-development.yml
  - >
      ansible-playbook -i inventory -vv --connection=local
      install_files/ansible-base/securedrop-development.yml
  # Travis needs the config.py file to be owned by root. In other environments
  # it's the `securedrop_user` var.
  - sudo chown root:root securedrop/config.py
  - sudo sh -c "export DISPLAY=:1; cd securedrop/ && pytest -v --page-layout tests/ ; cat tests/log/firefox.log"
  - pip freeze -l
  - SECUREDROP_TESTINFRA_TARGET_HOST=travis testinfra -v testinfra/development/
  - make -k lint
after_success:
  cd securedrop/ && coveralls
