---
- name: Install apt package dependencies for Development environment.
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ development_dependencies }}"
  tags:
    - apt
    - development

- name: Install pip dependencies for SecureDrop.
  pip:
    requirements: "{{ securedrop_pip_requirements }}"
  tags:
    - pip
    - development

- name: Install pip dev dependencies.
  pip:
    requirements: "{{ securedrop_pip_dev_requirements }}"
  tags:
    - pip
    - development

- name: Install sass Ruby gem
  gem:
    name: sass
    version: "{{ securedrop_sass_ver }}"
    user_install: no
  sudo: yes
  tags:
    - development

- name: Find gem binary via which.
  command: which gem
  ignore_errors: yes

- name: Check for SASS gem via which
  command: which sass
  ignore_errors: yes

- name: Check for SASS gem on disk.
  command: ls -l /usr/local/bin/sass
  ignore_errors: yes

- name: Compile sass to css
  command: sass --update sass:static/css
  args:
    chdir: '{{ securedrop_repo  }}/securedrop'
  register: dev_sass_compile_result
  # Any changed files will be printed to stdout; use that to detect whether
  # the files have changed.
  changed_when: "'write ' in dev_sass_compile_result.stdout"
  tags:
    - development

# Setting at the system-wide level to apply to all users.
- name: Set SECUREDROP_ENV in bashrc.
  copy:
    dest: /etc/profile.d/securedrop_env.sh
    content: "export SECUREDROP_ENV=dev"
  tags:
    - environment
    - development
